eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  basic:
    enabled: false

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG


